# Generated by Django 5.1.1 on 2024-09-29 06:11

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "code_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=10,
                        max_length=20,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "payment",
                    models.DecimalField(decimal_places=2, default=2, max_digits=30),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("nap_vnd", "Nạp VNĐ"),
                            ("rut_vnd", "Rút VND"),
                            ("nap_usdt", "Nạp USDT"),
                            ("rut_usdt", "Rút USDT"),
                        ],
                        default="nap_vnd",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("fail", "Fail"),
                            ("success", "Success"),
                            ("waiting", "Waiting"),
                        ],
                        default="waiting",
                        max_length=50,
                    ),
                ),
                ("time_create", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
